apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.serviceMonitor.labels.app }}  
  
  endpoints:
  {{- range .Values.serviceMonitor.endpoints }}
    - port: {{ .port }}
      interval: {{ .interval }}
      path: {{ .path }}
  {{- end }}